### ISSUE TITLE
image previews should fit to browser window

### ISSUE THREAD

**Issue by Rabscuttler** [treebeardtech/treebeard#20]
![image](https://user-images.githubusercontent.com/1125376/78572620-9d80ba80-781f-11ea-881b-3851c3c56955.png)

**Comment by alex-remedios** [comment]
Fixed! https://treebeard.io/admin/b44c784b10/treebeard_nbextensions/b2afe2ec-5039-4cda-8586-f06c692dec54

<img width="1432" alt="Screenshot 2020-04-07 at 13 10 21" src="https://user-images.githubusercontent.com/57841277/78667589-24da3680-78d1-11ea-823e-e21a10fe6825.png">
