### ISSUE TITLE
.yml vs .yaml compatibility

### ISSUE THREAD

**Issue by smithara** [treebeardtech/treebeard#24]
I found that:
`treebeard.yaml` works but `treebeard.yml` does not, and
`enviornment.yml` works but `environment.yaml` does not

On submitting a job where `treebeard.yml` is used, I get:
```
Warning: treebeard.yaml file not found! `treebeard setup` fetches an example.
```

Then if using `environment.yaml`, it doesn't seem to be detected during the run (https://api.treebeard.io/6d7d4332aa/Swarm_quicklooks/e3944bd1-513d-4a57-9bb8-1c765eda72b8/build_logs)

FYI: I am starting to use treebeard for a new project to display recent Swarm data for outreach purposes (https://treebeard.io/admin/6d7d4332aa/Swarm_quicklooks/71c9af5b-16d3-4047-971d-bdff571c366e) - should be a cool way to use treebeard!

**Comment by alex-remedios** [comment]
fixed (merge: https://github.com/treebeardtech/treebeard/commit/ee6485df8fe57070fddeb92d096be354270c1279)
