### ISSUE TITLE
`notebooks` GitHub Action parameter support for sequences

### ISSUE THREAD

**Issue by thewtex** [treebeardtech/treebeard#29]
To supply a list of notebooks to test.

Maybe there is a way to do this already, but this seems intuitive to me. :-)

Example,

https://github.com/InsightSoftwareConsortium/itkwidgets/actions/runs/156866815

**Comment by alex-remedios** [comment]
Agh, yeah appreciate this -- was just looking for the docs but I believe actions do not yet support list inputs frustratingly. Will look into this though.

**Comment by thewtex** [comment]
Thanks @alex-treebeard !

**Comment by alex-remedios** [comment]
@thewtex btw you *can* currently test multiple notebooks if you can express them in a single glob pattern via the action input e.g.

`notebooks: 'examples/*ipynb'`

and if you prefer you can use a yaml list to pass in multiple globs via the treebeard.yaml

```yaml
# treebeard.yaml
notebooks:
  - "examples/*ipynb"
  - "some_other.ipynb"
```

**Comment by thewtex** [comment]
@alex-treebeard cool, thanks for the tip -- testing in https://github.com/InsightSoftwareConsortium/itkwidgets/pull/363

**Comment by alex-remedios** [comment]
Fixed in master: https://github.com/alex-treebeard/Cirq/actions/runs/366541504/workflow

Will cut a release in the next week or so.
