### ISSUE TITLE
run treebeard on Windows images

### ISSUE THREAD

**Issue by Rabscuttler** [treebeardtech/treebeard#31]
The treebeard Github Action should run on Windows images as provided by Github Actions. 

Work in progress to test this functionality here [https://github.com/treebeardtech/treebeard/pull/30](https://github.com/treebeardtech/treebeard/pull/30)

Currently treebeard hangs in the action.

**Comment by alex-remedios** [comment]
remove usage of bash from the action typescript -- now have a dockerless windows runner integration test
