### ISSUE TITLE
`cell_execution_timeout_seconds`

### ISSUE THREAD

**Issue by habi** [treebeardtech/treebeard#42]
I have a notebook that can take a *really* long time, because it has to download several GB of data.
It's for a reproducible research project, available at https://github.com/habi/zmk-tooth-cohort

I'd like to run your GitHub action with https://github.com/habi/zmk-tooth-cohort/actions/runs/320495779/workflow but it complains about too long execution time.
I thus added `cell_execution_timeout_seconds: "2000"` to the treebeard YAML file.

But now the workflow complains about a warning, e.g.

````
Warning: Unexpected input(s) 'cell_execution_timeout_seconds', valid inputs are ['api-key', 'notebooks', 'docker-username', 'docker-password', 'docker-image-name', 'docker-registry-prefix', 'use-docker', 'debug', 'path', 'usage-logging']
2
````
How can I let Treebeard wait for the execution for a long time?

**Comment by jaimergp** [comment]
This is a configuration option you need in a file named `treebeard.yaml`, located at the root of your repo. [Like this](https://github.com/volkamerlab/TeachOpenCADD/blob/packaging/treebeard.yaml#L1)

**Comment by habi** [comment]
Thanks for the pointer, that was not clear for me.
