### ISSUE TITLE
Excluding notebooks and/or cells in notebooks from execution

### ISSUE THREAD

**Issue by spors** [treebeardtech/treebeard#58]
Single notebooks or single cells in notebooks might not be able to run on a virtual machine, e.g. due to missing hardware or data. This could be addressed for instance by adding an `exclude_notebook` action input to the API. Excluding cells from execution could be realized by checking for some specific key in the cell metadata.

**Comment by alex-remedios** [comment]
Hey @spors, thanks for taking the time to report this.

RE ignoring whole notebooks: Treebeard can do this with

```yaml
  uses: treebeardtech/treebeard@master
  with:
    ignore: |
      a.ipynb
      c/*.ipynb
```

See all action inputs here: https://github.com/treebeardtech/treebeard/blob/master/action.yml and an [example](https://github.com/alex-treebeard/Cirq/blob/fix_transform_notebook/.github/workflows/tb.yml)


RE ignoring expected exceptions in cells, I am working on a lower level [library](https://github.com/treebeardtech/nbmake) which will permit this and a lot more. So let me know if you have any interesting use cases or requirements.

**Comment by spors** [comment]
Sorry I have missed this option. Works perfect for entire notebooks!

**Comment by alex-remedios** [comment]
hey @spors I'm not sure where you got to with this but if using the treebeard action I'd recommend looking at migrate to [nbmake](https://github.com/treebeardtech/nbmake) which is faster and more portable.
