### ISSUE TITLE
Treebeard does not install on python 3.5

### ISSUE THREAD

**Issue by bill3tt** [treebeardtech/treebeard#7]
Going through the [install documentation](https://treebeard.readthedocs.io/en/latest/#install-treebeard) I was unable to `pip install treebeard`.

```
(treebeard-env) ➜  treebeard git:(master) ✗ pip install treebeard
ERROR: Could not find a version that satisfies the requirement treebeard (from versions: none)
ERROR: No matching distribution found for treebeard
(treebeard-env) ➜  treebeard git:(master) ✗ pip --version
pip 20.0.2 from /Users/ianbillett/work/treebeard/treebeard-env/lib/python3.5/site-packages/pip (python 3.5)
(treebeard-env) ➜  treebeard git:(master) ✗ python --version
Python 3.5.4
```
However, when running the virtualenv with python3.8 it installed fine.

```
➜  treebeard git:(master) ✗ virtualenv -p /usr/local/Cellar/python@3.8/3.8.2/bin/python3.8 py38
Running virtualenv with interpreter /usr/local/Cellar/python@3.8/3.8.2/bin/python3.8
Using base prefix 
...
Installing setuptools, pip, wheel...done.
➜  treebeard git:(master) ✗ source py38/bin/activate
(py38) ➜  treebeard git:(master) ✗ pip install treebeard
Collecting treebeard
  Downloading treebeard-0.0.60-py3-none-any.whl (16 kB)
...
```

Unless you are relying on specific features from a minor 3.x release, I would try and make `treebeard` work on all 3.x versions.

If not, please be more explicit in the documentation so that I am the only person to go through this flow :)

**Comment by alex-remedios** [comment]
Thanks for raising this Ian, treebeard relies on format [string literals and variable type annotations](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498) quite extensively (shout out to [pyright](https://github.com/microsoft/pyright)), so I've updated the docs to explicitly require 3.6+
